services:
  postgres:
    image: postgres:13-alpine
    environment:
      # .env の変数を展開（docker-compose はカレントディレクトリの .env を自動で読み込む）
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      # シェルのパラメータ展開の構文
      # もし環境変数 POSTGRES_PORT が定義されていて空でなければその値を使い、定義されていない（または空の場合）ならば代わりに 5432 を使う
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF__SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana

# volumes:
  # pgdata:
  # grafana-storage:
