"""set nullable false to all tables

Revision ID: 33fa13a73075
Revises: 704b8f937652
Create Date: 2025-04-06 00:04:55.986129

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33fa13a73075"
down_revision: Union[str, None] = "704b8f937652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "western_astrology_statuss",
        "required_info",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "western_astrology_statuss", "result", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "western_astrology_statuss",
        "result_voice_path",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "western_astrology_statuss",
        "result_voice_path",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "western_astrology_statuss", "result", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "western_astrology_statuss",
        "required_info",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
