apiVersion: 1

datasources:
  - name: "My PostgreSQL"
    type: "postgres"
    # Grafana から PostgreSQL へ接続する際の方式。
    # "proxy" を指定すると、GrafanaサーバーがDB接続の仲介を行います。
    access: "proxy"
    # PostgreSQL のホスト:ポート
    url: "postgres:5432"

    # 接続先のデータベース名
    database: "db_for_postgres"

    # 接続に使うユーザー名
    user: "user_for_postgres"

    # パスワードは secureJsonData に書くとマスクされます。
    secureJsonData:
      password: "password_for_postgres"

    # その他の接続情報
    jsonData:
      # SSLを使わない場合は"disable"。必要に応じて"require"などに変更
      sslmode: "disable"
      # PostgreSQL のバージョンを指定しておくとクエリ補完が最適化される(任意)
      postgresVersion: 1200

    # デフォルトのデータソースにしたい場合は true
    isDefault: true

    # ダッシュボード上でこの設定が編集可能かどうか
    editable: true